# fly.toml app configuration file generated for shop1login on 2024-10-21T22:39:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shop1login'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
